### PR TITLE
feat: use ConcurrentMap to replace map and mutex

### PR DESCRIPTION
**Pull request by RealBar**
Compared to map + sync.Mutex, ConcurrentMap is proved reliable and more efficient

### CODE REVIEW

**Comment by xtaci** [comment]
how is this compared with sync.Map?

**Comment by xtaci** [comment]
if there's only one link, the benefit from your algorithm is only the xxhash  algorithm right? the locking part is still the RLock?

How about caching + sync.Map?

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/commit/608bd97d7ba75e913e7a11c09c771add11c6d7d5

**Comment by RealBar** [comment]
segment lock also helps a lot

**Comment by RealBar** [comment]
benckmark is here
BenchmarkConcurrentMap_Write-8           4402040               344 ns/op
BenchmarkSyncMap_Write-8                 1000000              1869 ns/op
BenchmarkConcurrentMap_ReadWrite-8        398430              2947 ns/op
BenchmarkSyncMap_ReadWrite-8              365456              3240 ns/op
BenchmarkMapMutex_ReadWrite-8             336242              3683 ns/op

**Comment by xtaci** [comment]
For random r/w, segment lock is efficient surely.

But in kcp-go, for most of the time, just read lock is required to retrieve the session object. 

Write lock only happens twice(1. connection establishment, 2. connection termination)

**Pull request closed without merging**
