### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Stuff is now in separate commits, so you can cherry-pick, yet the last one is the most important one to me.

### CODE REVIEW

**Comment by xtaci** [comment]
i've cherry-picked commits until 1f2dfd6899d74b6a016917076f4e7d0fecd8e442

**Comment by AudriusButkevicius** [comment]
And what's wrong with the last two?

**Comment by xtaci** [comment]
1. some people are using the old API, and I want to keep it for the moment.
2. some tests cannot pass, and  I do not have confidence on it's correctness until I reviewed it carefully.

so for the moment, I can only merge those that i can make sure of.

**Comment by AudriusButkevicius** [comment]
So I addressed the test breakages, yet you closed the PR before the commits got updated.
Would you accept a PR which retains the old API, and add a new function which allows passing in the net.PacketConn?

**Comment by xtaci** [comment]
sure!

**Pull request closed without merging**
