### PR TITLE
Allow passing net.PacketConn

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
So the API is still compatible, yet I am able to pass a connection in to perform NAT traversal.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Also the tests should pass...

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/pull/24/files#diff-801d2c9dc8234c70b6c954d643436df1R105
I think you can't just reference to a fec object. A fec object is stateful and can only be used in only one session.

**Comment by AudriusButkevicius** [comment]
What about BlockCrypt?

**Comment by AudriusButkevicius** [comment]
Judging at the old code, block can be reused.
Addressed the FEC issue.

**Comment by xtaci** [comment]
newFEC in ListenWithOptions may fail and l.fec may be nil, also accessing member of member is really awful.

**Comment by AudriusButkevicius** [comment]
I'll add a copy method, and use that

**Comment by AudriusButkevicius** [comment]
That sadly won't happen for another 2 weeks as I am goijg away on hiliday.

**Comment by xtaci** [comment]
have a good holiday

**Comment by AudriusButkevicius** [comment]
Actually, found a few minutes to add it, before I depart.

**Comment by xtaci** [comment]
d21fc163-2a21-4d32-b008-5d81df79df9f


what about if I assign them both, then the sequence of the parameters will determine which will be overwritten.

**Comment by AudriusButkevicius** [comment]
Sure, and why is that wrong?

**Comment by xtaci** [comment]
the result will be different between the following:
```
newUDPSession(l, newFEC())
```
```
newUDPSession(newFEC(), l)

```

**Comment by AudriusButkevicius** [comment]
Sure, but what you'd expect to happen?

**Comment by xtaci** [comment]
I would prefer a consistent behavior，without worrying about the sequence of parameters.

**Comment by AudriusButkevicius** [comment]
This method is somewhat internal hence why I think we can allow it to be inconsistent, yet I guess we would then have to limit possibility from the client API.

**Comment by xtaci** [comment]
I think simplify by taking parameters out of *Listener would be enough.

**Comment by AudriusButkevicius** [comment]
Yet that doesn't prevent people from providing multiple instances of fec and so on, so I think it's a moot problem we are trying to solve, and people who misuse the api can face the consequences.

**Comment by AudriusButkevicius** [comment]
So I am back.
What's the latest with this?

**Comment by xtaci** [comment]
I think raddr & net.PacketConn parameters in Dial function are semantically conflicted,
why not add another API, named DialWithConn? like DialContext in go1.7

**Comment by AudriusButkevicius** [comment]
No, they are not conflicting, as one is providing where to dial, and the other one provide via what to dial, which is exactly the case here that is needed for stun.

**Comment by xtaci** [comment]
please make another PR for this, this branch has conflicts.

**Comment by AudriusButkevicius** [comment]
I can just rebase this PR

**Comment by xtaci** [comment]
ok cool

**Comment by AudriusButkevicius** [comment]
rebased

**Comment by xtaci** [comment]
found another problem:
```
401 // writeTo wraps write method for client & listener
402 func (s *UDPSession) writeTo(b []byte, addr net.Addr) (int, error) {
403     if s.l == nil {
404         if nc, ok := s.conn.(io.Writer); ok {
405             return nc.Write(b)
406         }
407     }
408     return s.conn.WriteTo(b, addr)
409 }
```

if you pass in a conn and s.l == nil, how can i tell the conn has Write method?

**Comment by AudriusButkevicius** [comment]
Took me a while to understand the question. The reason it works in my specific case is because my net.PacketConn has a wrapper that deals with that, but you are right, it won't work in the generic case.

Can we remove the write wrapper and use WriteTo everywhere instead?

**Comment by xtaci** [comment]
Write/WriteTo has different cost in syscall, Write() in UDP is about 4 times faster than WriteTo(). Low-end router devices benefit a lot from connected UDP.

**Comment by AudriusButkevicius** [comment]
Sure, so do you have any suggestions?
Golang doesn't provide a way to check if a given packet conn is connected or not. Best I can come up with is checking if the interface satisfies udpconn and check if it has a remote address (whichI hope is the way you identify if the udpconn is connected or not.

**Comment by xtaci** [comment]
it's really a hard problem, I think to make a new PacketConn interface may solve this.

**Comment by AudriusButkevicius** [comment]
As in

ConnectedPacketConn {
  net.PacketConn
  Connected() bool
}

?

**Comment by xtaci** [comment]
I mean some wrappers, the api caller show bind Write() method to conn.Write() or conn.WriteTo()

**Comment by AudriusButkevicius** [comment]
Can you elaborate? I am not sure I understand what you mean.

**Comment by xtaci** [comment]
401 // writeTo wraps write method for client & listener
402 func (s *UDPSession) writeTo(b []byte, addr net.Addr) (int, error) {
403     if s.l == nil {
404         if nc, ok := s.conn.(io.Writer); ok {
405             return nc.Write(b)
406         }
407     }
408     return s.conn.WriteTo(b, addr)
409 }

we do not need this method, we just wrap the connected UDP 

WrappedUDPConn implements net.PacketConn {
     WriteTo(b, addr) {
          this.conn.Write(b)   // ignore the addr for connected socket.
    }
}

**Comment by AudriusButkevicius** [comment]
Oh so you mean do the wrapping internally in the lib for connections we know are connected?

**Comment by xtaci** [comment]
exactly,  callers know this.

**Comment by AudriusButkevicius** [comment]
Great idea. I'll do this tonight hopefully.

**Comment by AudriusButkevicius** [comment]
Added the wrapper. Made it public as others might have use-cases for it too.

**Comment by xtaci** [comment]
good job.
but i'm still not comfort with the API, i'll try some step by step method of add support for conn.

**Comment by xtaci** [comment]
@AudriusButkevicius  see the latest commit:
https://github.com/xtaci/kcp-go/commit/6a13e8ae00d631cb8aea417b3ed4f1d495ea6241

**Comment by AudriusButkevicius** [comment]
I thiink yhe API is now much worse, as there are two functions which are not obvious why are they there for, and yet we still have the Options mess convoluted in some functions.

Anyways that woll be good enough for my usecase tho.

**Comment by xtaci** [comment]
opts are mess,  i think i 'll remove that.  
to clarify the new functions:
NewConn + ServeConn are the real APIs to talk with KCP protocol on a PacketConn

net.UDPConn is a special case of PacketConn. Provided as a default.

**Pull request closed without merging**
