### PR TITLE
Key connections by addr+convId, reset cache key on disconnect

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Trying to push this through once more so that we don't have to maintain a fork and so that Debian folks wouldn't need to package two packages.

### CODE REVIEW

**Comment by xtaci** [comment]
can you update the tests as well?

**Comment by AudriusButkevicius** [comment]
Done I think?

**Comment by xtaci** [comment]
LGTM

**Comment by sheepbao** [comment]
don't use `key := fmt.Sprintf("%s/%d", addr, conv)`, use a struct :
```
type key struct {
    add string
    conv int32
}
```
faster than fmt.Sprintf()

**Comment by xtaci** [comment]
@sheepbao please PR

**Pull request merged**
